### ISSUE TITLE
Allow V2 of the monsieurbiz/sylius-rich-editor-plugin package

### ISSUE THREAD

**Issue by DieterHolvoet** [monsieurbiz/SyliusHomepagePlugin#3]
If I'm correct version 2 is backwards compatible, so it would be useful to allow that version in this package.

**Comment by DieterHolvoet** [comment]
Looks like I was wrong, the Twig function name changed. I changed the Twig function name & restricted the version to only support V2, unless you decide to add an alias for the old function name to ensure backwards compatibility.

**Comment by maximehuran** [comment]
I am currently working on the plugin to upgrade the rich editor version and improve code quality.
You can see pull request #5.
Recipe and test github workflows are good, I am correcting the fail on scrutinizer build.

**Comment by jacquesbh** [comment]
Closed by #5
