### ISSUE TITLE
issue from v1.0.2

### ISSUE THREAD

**Issue by benoitmidon** [monsieurbiz/SyliusHomepagePlugin#31]
Hi, since the release [v1.0.2](https://github.com/monsieurbiz/SyliusHomepagePlugin/releases/tag/v1.0.2) we can't update our project anymore :

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/7021829/227473093-a92533d2-1c9e-46d7-bf11-61e0a8e8c03d.png">

We had to force the 1.0.1. version

any idea ?

**Comment by benoitmidon** [comment]
any idea ??

**Comment by delyriand** [comment]
Hi @benoitmidon,

I think this issue is fix with the PR #32.
Can you try with the `dev-master` version of this plugin? 

If it's good, we will be creating a release soon.
If not, can you give me your version of sylius?
